version: '3'
services:
  tomcat:
    restart: always
    image: tomcat:8.5.56-jdk8-openjdk
    container_name: tomcat
    ports:
      - 8080:8080
    volumes:
      - ./:/usr/local/tomcat/webapps/
    environment:
      TZ: Asia/Shanghai

